int test_vidioc_enum_fmt(int , uint32_t, uint32_t);
int test_vidioc_enum_framesizes(int , uint32_t, uint32_t, uint32_t, uint32_t);
int test_vidoc_enum_frameintervals(int , uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
int test_vidoc_try_fmt(int , uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
int test_vidioc_s_fmt(int , uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
int test_vidioc_s_parm(int ,uint32_t, uint32_t, uint32_t);
int test_vidioc_reqbufs(int , uint32_t, uint32_t, uint32_t, uint32_t);
int test_vidioc_qbuf(int , uint32_t, uint32_t, unsigned long, unsigned long);
int test_vidioc_dqbuf(int , uint32_t );
int test_vidioc_queryctrl(int , uint16_t , uint16_t);
int test_vidioc_ext_queryctrl(int , uint16_t , uint16_t );
int test_vidioc_querymeny(int , uint16_t , uint16_t , uint32_t );
int test_vidioc_s_ctrl(int , uint16_t , int32_t );
int test_vidioc_ctrl(int  );
int test_vidioc_s_ext_ctrl(int, uint16_t, uint16_t, int32_t);
int test_vidioc_g_ext_ctrl(int, int);
int test_do_halfpush(int);
int test_streamon(int , const int );
int test_streamoff(int, const int);
int test_takepict_start(int , uint32_t );
int test_takepict_stop(int , bool);
