# Specify the relative path to the top of repository
SPRITZER_TOP_REL := ../../../../../../../..

PROJECT_NAME := configdata
CHIP_NAME := SPRITZER
CONFIG_COMPILER := RVDS

##### Specify the configuration source code #####
CONFIG_SRCS = config.c


##############################################################
########## Basically, should not need to edit below ##########

.PHONY : all
all:

include $(SPRITZER_TOP_REL)/Common.mk
include $(MK_PATH)/BuildConfig.mk
