int stillc(int, int, int, int, int);
int still_jpeg(int, int, int, int, int);
int shutter_plus(int, int, int, int, int, int, int);
int still_yuv(int, int, int, int, int);
int videostart(void);
int video_delete(void);
int streamoff(void);
int change_brightness(int);
int change_contrast(int);
int change_saturation(int);
int change_hue(int);
int change_awb(int);
int change_redbalance(int);
int change_bluebalance(int);
int change_gamma(int);
int change_exposure(int);
int change_hflip(int);
int change_vflip(int);
int change_sharpness(int);
int change_colorkill(int);
int change_colorfx(int);
int change_check(int);
int buffer_test(int);
int check_device(void);
int check_format(int, int, int, int);
int change_jpg_compress_quority(int);
int change_autoexpo(int);
int change_expoabs(int);
int change_expomete(int);
int change_whitebalace(int);
int change_widedinamicrange(int);
int change_3a(int);
int change_iso(int);
int change_isoauto(int);
int change_af(int);
int repeat_create_delete(void);


int still_shutter(int, int, int, int, int, int);
int still_shutter_close(int, int, int, int, int, int);
int sub_shutter(int, int, int, int, int, int, int);
int camera_prepare__test_sub(int, enum v4l2_buf_type, uint32_t, uint32_t, uint16_t, uint16_t, uint8_t, int, int, uint16_t, uint16_t);
int camera_prepare_test(int, enum v4l2_buf_type, uint32_t, uint32_t, uint16_t, uint16_t, uint8_t, int, int);
