#====================================================================#
#
#	File Name: Makefile
#
#	Description: Makefile creates binaries for decoder
#
#	Notes: (C) Copyright 2016 Sony Corporation
#
#	Author:	Masahiro TAKEYAMA
#
#====================================================================#

all:
	cd build; make

run:
	cd build; ./test>AudioManager.txt; cd ../

clean:
	cd build; make allclean
